#!/usr/bin/env ansible-playbook
---
- hosts: all
  gather_facts: yes
  roles:
    code_server_password: SuperSecret
    code_server_user: "{{ ansible_user_id }}"
    code_server_host: 0.0.0.0
    code_server_port: 8443
    code_server_tls_cert: /etc/letsencrypt/live/example.com/fullchain.pem
    code_server_tls_key: /etc/letsencrypt/live/example.com/privkey.pe
