#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  gather_facts: yes
  become: yes
  roles:
    - name: code_server
      code_server_password: SuperSecret
      code_server_user: "{{ ansible_user_id }}"
      code_server_host: 0.0.0.0
      code_server_port: 8443
