- name: Check code-server binary exists
  stat:
    path: "{{ bin_dir }}/code-server"
  register: code_server_exists

- name: Check code-server version
  command: code-server --version
  register: code_server_version
  when: code_server_major != '2' and
        code_server_exists.stat.exists
  changed_when: no

- name: Check code-server v2 version
  shell: "set -o pipefail; code-server --version | head -1 | cut -d' ' -f3"
  args:
    executable: /bin/bash
  register: code_server_version
  when: code_server_major == '2' and
        code_server_exists.stat.exists
  changed_when: no
