- name: Copy TLS certificate
  copy:
    remote_src: "{{ tls_cert_remote }}"
    src: "{{ tls_cert }}"
    dest: "{{ code_server_data_dir }}/tls.cert"
    mode: 0440
  notify: Restart code-server
  when: tls_cert is defined

- name: Copy TLS key
  copy:
    remote_src: "{{ tls_key_remote }}"
    src: "{{ tls_key }}"
    dest: "{{ code_server_data_dir }}/tls.key"
    mode: 0440
  notify: Restart code-server
  when: tls_key is defined
