---
- name: Include RedHat specific tasks
  include_tasks: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Include Debian specific tasks
  include_tasks: Debian.yml
  when: ansible_os_family == "Debian"

- name: Check systemd version
  shell: "set -o pipefail; systemctl --version | head -1 | cut -d' ' -f2"
  args:
    executable: /bin/bash
  register: systemctl_version
  changed_when: no

- name: Check code-server
  include_tasks: check-code-server.yml

- name: Install code-server
  include_tasks: install-code-server.yml

- name: Configure code-server
  include_tasks: configure-code-server.yml

- meta: flush_handlers

- name: Enable code-server service
  become: yes
  systemd:
    name: code-server
    enabled: yes

- name: Report
  include_tasks: report.yml

- name: Sanity Test
  include_tasks: tests.yml
