name: ansible-galaxy import

on: [push]

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: ansible-galaxy import --api-key ${API_KEY} ${GITHUB_REPOSITORY%/*} ${GITHUB_REPOSITORY#*/}
      env:
        API_KEY: ${{ secrets.API_KEY }}
